In [26]:
from preprocess import preprocess
from model import Net
import torch
batch_size=2
features_num=4
data_path='t.csv'
vocab_path='vocab/vocab.txt'
config_path="config/model_config.json"
model_path='pytorch_model.bin'
clip=1e-1
pos_tensor=torch.ones(batch_size,features_num).detach()
neg_tensor=torch.zeros(batch_size,features_num).detach()

In [27]:
model=Net(config_path=config_path,
    model_path=model_path,
    output_features=features_num
)

In [28]:
dataloader=preprocess(data_path=data_path,vocab_path=vocab_path,features_nums=features_num,batch_size=batch_size)

In [29]:

for batch,(line,pos,neg) in enumerate(dataloader) :
    output=model(line)
    print(f"output{output}")
    loss_pos=-torch.log(output)*pos
    print(f"pos:{loss_pos}")
    loss_neg=-torch.log(1-output)*neg
    print(f"neg:{loss_neg}")
    loss=loss_pos+loss_neg
    print(loss)
    print(loss.sum(dim=1))

outputtensor([[1.0000, 0.2748, 0.4752, 0.3599],
        [0.3691, 0.2495, 1.0000, 0.9044]], grad_fn=<DivBackward0>)
pos:tensor([[-0.0000, 1.2917, 0.7439, 0.0000],
        [0.9967, 1.3884, -0.0000, 0.0000]], grad_fn=<MulBackward0>)
neg:tensor([[   nan, 0.3213, 0.6448, 0.4461],
        [0.0000, 0.2870,    inf, 0.0000]], grad_fn=<MulBackward0>)
tensor([[   nan, 1.6130, 1.3887, 0.4461],
        [0.9967, 1.6754,    inf, 0.0000]], grad_fn=<AddBackward0>)
tensor([nan, inf], grad_fn=<SumBackward1>)


tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]])